on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: We test it locally with act
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Run the custom action, get Pokemon name
        uses: ./ # Uses an action in the root directory
        id: pokemon
        with:
          pokemon_id: 150
    
      - name: Get the pokemon
        run: echo "${{ steps.pokemon.outputs.pokemon_name }} attack"